services:
  vancouver-crime-predictor:
    image: tirthjoship/vancouver-crime-predictor:f166a0c
    ports:
      - "10000:8888"
    volumes:
      - .:/home/jovyan/work
    platform: linux/amd64
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --ServerApp.token=''
      --ServerApp.password=''
      --ServerApp.disable_check_xsrf=True
      --ServerApp.allow_origin='*'
      --ServerApp.allow_remote_access=True
