name: '522'
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.2.3
  - click=8.1.7
  - conda-lock=2.5.8
  - folium=0.18
  - ipykernel=7.1.0
  - nb_conda_kernels=2.5.1
  - altair=5.4.1
  - pip=25.3
  - scikit-learn=1.7.2
  - requests=2.32
  - jupyter=1.1
  - numpy=1.26.4
  - seaborn=0.13.2
  - jupyterlab=4.2
  - matplotlib=3.9.4
  - imbalanced-learn=0.12
  - pandera=0.26.1
  - ipywidgets=8
  - quarto=1.8.26
  - anywidget=0.9.21
  - pytest=8.3.4
  - pip:
      - kagglehub==0.3.4
      - deepchecks==0.19.1
      - vegafusion[embed]==2.0.1
      - vl-convert-python==1.7.0